# Generated by Django 5.0.4 on 2024-04-22 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "unique_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_time", models.DateField(auto_now_add=True)),
                ("userid", models.CharField(max_length=30)),
                ("current_total", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="MostActivelyTraded",
            fields=[
                (
                    "unique_key",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("insert_time", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField()),
                ("ticker", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "change_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("volume", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name="StocksPriceHistory",
            fields=[
                (
                    "unique_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_time", models.DateField(auto_now_add=True)),
                ("stock_name", models.CharField(max_length=50)),
                ("ticker", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="TopDailyGainers",
            fields=[
                (
                    "unique_key",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("insert_time", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField()),
                ("ticker", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "change_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("volume", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name="TopDailyLosers",
            fields=[
                (
                    "unique_key",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("insert_time", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField()),
                ("ticker", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "change_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("volume", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SimplyWealthApp.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockTransanctions",
            fields=[
                (
                    "transaction_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("stock_symbol", models.CharField(max_length=5)),
                ("transaction_type", models.CharField(default="buy", max_length=4)),
                ("stock_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_units", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_price_date", models.DateField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SimplyWealthApp.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserStockPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_symbol", models.CharField(max_length=5)),
                ("stock_units", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SimplyWealthApp.userprofile",
                    ),
                ),
            ],
        ),
    ]
