# Generated by Django 5.0.2 on 2024-04-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplyWealthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostactivelytraded',
            name='unique_key',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topdailygainers',
            name='unique_key',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topdailylosers',
            name='unique_key',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
