# Generated by Django 5.0.2 on 2024-04-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplyWealthApp', '0006_rename_transanction_id_stocktransanctions_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransanctions',
            name='stock_price_date',
            field=models.DateField(),
        ),
    ]
