# Generated by Django 5.0.4 on 2024-04-07 21:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplyWealthApp', '0011_stockspricehistory_ticker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostActivelyTraded',
            fields=[
                ('unique_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='TopDailyGainers',
            fields=[
                ('unique_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='TopDailyLosers',
            fields=[
                ('unique_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
