# Generated by Django 5.0.2 on 2024-02-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tick_symbol", models.CharField(max_length=5)),
                ("market_value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
