# Generated by Django 5.0.2 on 2024-04-01 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplyWealthApp', '0003_remove_userprofile_id_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransanctions',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('stock_symbol', models.CharField(max_length=5)),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_price_date', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimplyWealthApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserStockPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=5)),
                ('stock_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimplyWealthApp.userprofile')),
            ],
        ),
    ]
