# Generated by Django 5.0.2 on 2024-04-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimplyWealthApp', '0007_alter_stocktransanctions_stock_price_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransanctions',
            name='transaction_type',
            field=models.CharField(default='buy', max_length=4),
        ),
    ]
