# Generated by Django 5.0.4 on 2024-04-06 23:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SimplyWealthApp", "0008_stocktransanctions_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "unique_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_time", models.DateField(auto_now_add=True)),
                ("stock_name", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
