# Generated by Django 5.0.4 on 2024-04-07 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SimplyWealthApp", "0010_stockspricehistory_delete_stocks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockspricehistory",
            name="ticker",
            field=models.CharField(
                default=datetime.datetime(2024, 4, 7, 13, 57, 32, 519589), max_length=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stockspricehistory",
            name="stock_name",
            field=models.CharField(max_length=50),
        ),
    ]
